POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Usuário Indicado2",
  "email": "indicado2@gmail.com",
  "referrer": "bd6754cc-8b8c-434b-aa58-7c3e9b318c5f"
}

###

GET http://localhost:3333/invites/1f4c2622-2cc4-4eb1-a2b3-40b59aadf03e

###

GET http://localhost:3333/subscribers/1f4c2622-2cc4-4eb1-a2b3-40b59aadf03e/ranking/clicks

###
GET http://localhost:3333/subscribers/1f4c2622-2cc4-4eb1-a2b3-40b59aadf03e/ranking/count

###
GET http://localhost:3333/subscribers/1f4c2622-2cc4-4eb1-a2b3-40b59aadf03e/ranking/position

###
GET http://localhost:3333/ranking