POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Yan Garrido",
  "email": "yan4@gmail.com",
  "referrer": "6b8ac4e9-fa7d-4341-9599-628c8bdef27d"
}

###

GET http://localhost:3333/invites/6b8ac4e9-fa7d-4341-9599-628c8bdef27d

###

GET http://localhost:3333/subscribers/6b8ac4e9-fa7d-4341-9599-628c8bdef27d/ranking/clicks

###
GET http://localhost:3333/subscribers/6b8ac4e9-fa7d-4341-9599-628c8bdef27d/ranking/count

###
GET http://localhost:3333/subscribers/6b8ac4e9-fa7d-4341-9599-628c8bdef27d/ranking/position

###
GET http://localhost:3333/ranking